import '../models/parking_spot.dart';

class MockParkingData {
  static final Map<int, List<ParkingSpot>> spots = {
    // 2: Bãi đỗ Mỹ Đình
    2: [
      ParkingSpot(
        id: 101,
        code: 'Ô B1',
        status: ParkingSpotStatus.available,
        occupied: false,
        userId: '',
        paymentStatus: 'none',
        transactionAmount: 0,
        expectedDuration: 0,
        bookingStartTime: 0,
      ),
      ParkingSpot(
        id: 102,
        code: 'Ô B2',
        status: ParkingSpotStatus.occupied,
        occupied: true,
        userId: 'mock_user_1',
        paymentStatus: 'active',
        transactionAmount: 0,
        expectedDuration: 0,
        bookingStartTime: 0,
      ),
      ParkingSpot(
        id: 103,
        code: 'Ô B3',
        status: ParkingSpotStatus.available,
        occupied: false,
        userId: '',
        paymentStatus: 'none',
        transactionAmount: 0,
        expectedDuration: 0,
        bookingStartTime: 0,
      ),
      ParkingSpot(
        id: 104,
        code: 'Ô B4',
        status: ParkingSpotStatus.violationOrPending,
        occupied: false,
        userId: '',
        paymentStatus: 'pending_payment',
        transactionAmount: 20000,
        expectedDuration: 0,
        bookingStartTime: 0,
      ),
    ],
    // 3: Bãi đỗ Hoàn Kiếm
    3: [
      ParkingSpot(
        id: 201,
        code: 'Ô C1',
        status: ParkingSpotStatus.occupied,
        occupied: true,
        userId: 'mock_user_2',
        paymentStatus: 'active',
        transactionAmount: 0,
        expectedDuration: 0,
        bookingStartTime: 0,
      ),
      ParkingSpot(
        id: 202,
        code: 'Ô C2',
        status: ParkingSpotStatus.available,
        occupied: false,
        userId: '',
        paymentStatus: 'none',
        transactionAmount: 0,
        expectedDuration: 0,
        bookingStartTime: 0,
      ),
      ParkingSpot(
        id: 203,
        code: 'Ô C3',
        status: ParkingSpotStatus.reserved,
        occupied: false,
        userId: 'mock_user_3',
        paymentStatus: 'active',
        transactionAmount: 0,
        expectedDuration: 3600,
        bookingStartTime: 1770000000, // mock timestamp
      ),
      ParkingSpot(
        id: 204,
        code: 'Ô C4',
        status: ParkingSpotStatus.available,
        occupied: false,
        userId: '',
        paymentStatus: 'none',
        transactionAmount: 0,
        expectedDuration: 0,
        bookingStartTime: 0,
      ),
    ],
    // 4: Bãi đỗ Ba Đình
    4: [
      ParkingSpot(
        id: 301,
        code: 'Ô D1',
        status: ParkingSpotStatus.available,
        occupied: false,
        userId: '',
        paymentStatus: 'none',
        transactionAmount: 0,
        expectedDuration: 0,
        bookingStartTime: 0,
      ),
      ParkingSpot(
        id: 302,
        code: 'Ô D2',
        status: ParkingSpotStatus.available,
        occupied: false,
        userId: '',
        paymentStatus: 'none',
        transactionAmount: 0,
        expectedDuration: 0,
        bookingStartTime: 0,
      ),
      ParkingSpot(
        id: 303,
        code: 'Ô D3',
        status: ParkingSpotStatus.occupied,
        occupied: true,
        userId: 'mock_user_4',
        paymentStatus: 'active',
        transactionAmount: 0,
        expectedDuration: 0,
        bookingStartTime: 0,
      ),
      ParkingSpot(
        id: 304,
        code: 'Ô D4',
        status: ParkingSpotStatus.available,
        occupied: false,
        userId: '',
        paymentStatus: 'none',
        transactionAmount: 0,
        expectedDuration: 0,
        bookingStartTime: 0,
      ),
    ],
  };
}
